### ISSUE TITLE
Code Climate Coverage Buttons

### ISSUE THREAD

**Issue by RachBLondon** [FAC6/book#109]
Hi,

Good tutorial but add this to end to get data sent to code climate for badges:

Once everything is done,
Go to master and run the following commands:

```
npm run coverage


npm codeclimate
```

https://github.com/FAC6/book/blob/master/patterns/week3/codeclimate.md#how-to-implement-code-climate-code-coverage-score-with-tape-and-istanbul-will-not-work-with-a-forked-repo-or-branches

**Comment by Jbarget** [comment]
should all be good now, feel free to close the issue if you get a chance
