### ISSUE TITLE
week 5 file structure repo pictures

### ISSUE THREAD

**Issue by mk4111** [FAC6/book#115]
![repo_3](https://cloud.githubusercontent.com/assets/13470325/10430201/b52b24d0-70f5-11e5-9f9e-1d9da93800df.png)

![repo_2](https://cloud.githubusercontent.com/assets/13470325/10430198/b2dd81a0-70f5-11e5-9ba4-3bc15eaa8fa0.png)

![repo_1](https://cloud.githubusercontent.com/assets/13470325/10430209/bfa23b9c-70f5-11e5-90b4-dde9bbfe2200.png)

**Comment by iteles** [comment]
@mk4111 Did you use these images where you needed them? Can we close this issue?

**Comment by mk4111** [comment]
I don't know how I missed this but the answer is a yeeees!
