### ISSUE TITLE
Gitignore

### ISSUE THREAD

**Issue by RachBLondon** [FAC6/book#14]
Nice readme, very clear and easy to understand. However would be great to know why you might need to use the .gitignore  file.

Rach

**Comment by iteles** [comment]
@sohilpandya When closing an issue: if you haven't linked a commit to the issue then it's always useful to add a note as to what was done about it (even if you just decided it wouldn't get done, that's why `wontfix` is a standard github label) :blush:

**Comment by sohilpandya** [comment]
Thanks @iteles, wasn't aware of the wontfix label.
