### ISSUE TITLE
Branches.md

### ISSUE THREAD

**Issue by Joshua-Ronan-Phillips** [FAC6/book#18]
Great content! Some subheadings might be useful to group information.

**Comment by iteles** [comment]
@Joshua-Ronan-Phillips Do you know who wrote the content you're referring to? Could you please assign the issue to them so we know who is accountable for getting this done?

**Comment by mantagen** [comment]
(I don't know who wrote it originally) . Have made some changes, and am now going to close the issue. Please re-open with more specific issues if necessary
