### ISSUE TITLE
Who shuts down issues?

### ISSUE THREAD

**Issue by thegsi** [FAC6/book#22]
Are issues shut down automatically? Are they shut down after pull requests are merged?

What is the best protocol for closing issues?

**Comment by thegsi** [comment]
https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by thegsi** [comment]
One can include key words in commit messages to close issues. It is also possible to close them using key requests with special keyword syntax .

**Comment by iteles** [comment]
@thegsi Exactly! In the same way that you can (and should) include the issue URL in your commit message, you can also include the words 'resolve' or 'fixes' as per your link above. These will automatically close an issue when merged into master. 

You can of course also close them manually.

Can I suggest you add a super small PR to add this information to the week 1 book readmes (like [to this one for example](https://github.com/FAC6/book/blob/master/patterns/week1/gitcommandREADME.md) and assign it to one of your colleagues to merge in? If you use the _'fixes' keyword and this issue URL it'll automatically close this issue :wink: (very meta)

**Comment by mantagen** [comment]
@thegsi  is this done?
Trying to get some of these issues closed :)

**Comment by iteles** [comment]
@mantagen :raised_hands: Thanks!

**Comment by thegsi** [comment]
Doing this now, so with any luck it will close automatically!

**Comment by thegsi** [comment]
Can we merge the pull request.

**Comment by thegsi** [comment]
Could someone merge the pull request please? Thanks.
