### ISSUE TITLE
Challenge

### ISSUE THREAD

**Issue by sofer** [FAC6/book#30]
@nelsonic you and Bes have already done one for FAC5 that I believe can be re-used.

**Comment by iteles** [comment]
For Tuesday, added in PR https://github.com/foundersandcoders/morning-challenge/pull/5, https://github.com/foundersandcoders/morning-challenge/pull/7 and solution at https://github.com/foundersandcoders/morning-challenge/pull/8.

**Comment by iteles** [comment]
For Wednesday, added in PR https://github.com/foundersandcoders/morning-challenge/pull/10
