### ISSUE TITLE
Week 2 project needs to be added

### ISSUE THREAD

**Issue by sofer** [FAC6/book#31]
Not needed until Wednesday.

**Comment by iteles** [comment]
@sofer Do you want to add in the baseline learning outcomes and project from FAC5 and we'll add the edits ontop so we track the changes (whether they're minor or a completely different project in the end)?

**Comment by sofer** [comment]
@iteles the learning outcomes are referenced here: http://fac6.foundersandcoders.org/patterns/week2/index.html
