### ISSUE TITLE
Week 1 Stop, Go, Continue action points

### ISSUE THREAD

**Issue by sofer** [FAC6/book#33]
@iteles I don't think we have to capture all the suggestions from the Friday session, but a summary of the main action points would be super helpful.

https://github.com/FAC6/book/blob/master/sgc/week1.md

**Comment by iteles** [comment]
As we discussed, I'll intersperse them between a dedicated SGC area (I think having them all together might be more productive than having to click in and out of 8 files) and putting them straight into the timetable as actionable (and trackable via version history) changes :+1:

**Comment by sofer** [comment]
@iteles have made a merge request with SGC now in a single README.
