### ISSUE TITLE
Base timetable to be added for every week?

### ISSUE THREAD

**Issue by iteles** [FAC6/book#61]
[From experience](github.com/foundersandcoders/playbook), we know that not everyone reads all of the notes and stop go continue changes before they start their week of teaching. 

I suggest we trial having the base timetable in every week to give people a structure to _alter_ for their weeks (as a hint that one already exists) rather than a blank page.

What do you reckon @sofer? I'm happy to make this happen.

**Comment by sofer** [comment]
@iteles agreed.

**Comment by iteles** [comment]
Linked to: https://github.com/FAC6/book/pull/68

**Comment by sofer** [comment]
@iteles agreed.

**Comment by iteles** [comment]
We're creating the following week's timetable during the current week's stop go continue and this is working fine.
