### ISSUE TITLE
adds pics for dev tools readme

### ISSUE THREAD

**Issue by Conorc1000** [FAC6/book#8]
![color-css-shot](https://cloud.githubusercontent.com/assets/12072531/9878149/3bf77808-5bb9-11e5-95d0-00035dc0e225.png)
![dev-tool](https://cloud.githubusercontent.com/assets/12072531/9878154/3eec8076-5bb9-11e5-93ee-1e1361751313.png)

![css-shot](https://cloud.githubusercontent.com/assets/12072531/9878166/465897dc-5bb9-11e5-8b11-462cfc1f7579.png)

**Comment by iteles** [comment]
@Jbarget If you've used the image and your update is in master, could you please close this issue?
