### ISSUE TITLE
Code quality control with Code Climate - question

### ISSUE THREAD

**Issue by RachBLondon** [FAC6/book#93]
Thanks for this readme, overall its very useful, but I am have difficulty setting up the code coverage using code climate on my own.

I am having trouble when I `npm run codeclimate`
I think this is because I am confused as to how to  change the path of lcov.info to reflect our file structure

https://github.com/FAC6/book/blob/master/patterns/week3/codeclimate.md#how-to-implement-code-climate-code-coverage-score-with-tape-and-istanbul-will-not-work-with-a-forked-repo-or-branches

**Comment by des-des** [comment]
can you show a screenshot of your file structure and a copy of the script you are trying to run?

**Comment by RachBLondon** [comment]
No worries, I understand the file path route now :-)
